### ISSUE TITLE
Optional Requirements

### ISSUE THREAD

**Issue by flangofas** [QoboLtd/test.qobo.biz#15]
Tester should provide a list of options before testing the site because not all projects have the same requirements.

For example,
- Powered by Qobo
- Copyright

Could be disabled by client's request.

Also, the project will become more generic and other vendors can use it :smile:

**Comment by mamchenkov** [comment]
@flangofas 

feel free to send a Pull Request. ;)

**Comment by flangofas** [comment]
@mamchenkov Sure! :smile:
